### ISSUE TITLE
Does this package plan to support subscripts and superscripts?

### ISSUE THREAD

**Issue by georgewsinger** [Christoph-D/latex-unicode-math-mode#1]
Example: x₁ and x⁵?

**Comment by Christoph-D** [comment]
For now, there are no such plans.

The reason for not having superscripts is technical (maybe caused by my limited LaTeX skills) and explained here: https://github.com/Christoph-D/latex-unicode-math-mode/blob/master/latex-unicode-math-mode.el#L98
tl;dr: I do not know how to handle multiple superscripts like $X'²$.

The reason for not having subscripts is to be consistent with not having superscripts and that they looked really bad in the font I was using when I wrote this package.  So the case for not having subscripts is much weaker, but because I mostly stopped writing LaTeX recently, this is currently not a priority.
